__title__ = "virtualbox"
__author__ = "Michael Dorman"
__author_email__ = "mjdorma+pyvbox@gmail.com"
__maintainer__ = "Seth Michael Larson"
__maintainer_email__ = "sethmichaellarson@gmail.com"
__version__ = "2.1.0"
__license__ = "Apache-2.0"
__url__ = "https://github.com/sethmlarson/virtualbox-python"
